// docs.jsx — the user-manual content behind every ⓘ button (see InfoDoc.jsx).
// One entry per tab / sub-tab. Written to be LEARNED from, not just consulted:
// each doc says why the tab exists, how to read every panel or column, where the
// same data appears on other tabs (and why), exactly which numbers are live vs
// hardcoded-official vs model-estimated vs missing (the no-proxy-data house
// rule), and where to go to research further.
//
// Integrity classes: live / official (hardcoded transcription of a published
// fact, source cited) / model (estimated — never present as observed fact) /
// gap (unavailable → shown blank, never proxied).

export const DOCS = {

  // ═══════════════════════ EM RULES ═══════════════════════
  rules: {
    title: "EM RULES — Willer/Chandran/Lam screener",
    tagline: "Which EM countries meet the book's backtested trade conditions today. A screener, not a backtest.",
    why: [
      "This tab screens the EM universe against the trading rules in Willer, Chandran & Lam, “Trading Fixed Income and FX in Emerging Markets: A Practitioner's Guide” (Wiley, 2020) — three Citi practitioners' distillation of what has historically worked in EM rates and FX. The book supplies the backtested evidence; this screen only answers “which countries satisfy each condition right now”. It does not re-run the backtests.",
      "Important honesty note: the R1…R11 numbering is OUR labelling (from the build plan), not the book's — the book doesn't number its rules. Where the book's digest records hard evidence (a Sharpe, a hit count) it is quoted below; where it records only a qualitative claim, that is said plainly. The digest's backtests end around 2018, so treat all of it as in-sample for today's trading.",
      "Rows are grouped by region and sorted by the R3 real-rate rank. One build per 12h (the ~150 daily histories are expensive against the LSEG quota); REBUILD forces a refresh.",
    ],
    howLabel: "COLUMN BY COLUMN",
    how: [
      { name: "POLICY / CPI Y/Y / CORE",
        what: "The country's current policy rate, headline CPI y/y and core CPI y/y — from LSEG economic-indicator and Reuters-poll series.",
        read: "These are the raw ingredients for R1–R5. CORE shows only where a core-CPI RIC is wired (BR MX PL HU ZA TR ID TH PH EG SG …) — it is blank for IN/CO/KR/MY among the profiled majors and for all frontier/GCC names. Blank, not proxied.",
        why: "Every rates rule in the book keys off where policy is relative to inflation and where the cycle is." },
      { name: "R1 CYCLE (chip: RECEIVE / PAY + 1Y−policy gap)",
        what: "The 1Y swap (or OIS) minus the policy rate. Chip says RECEIVE when the 1Y has crossed BELOW policy (the market is pricing cuts), PAY when it crosses above ahead of hikes; the date is when the state began. Implementation detail: the exact trigger bands (below −0.10 / above +0.25, with a neutral zone between) are house calibration to avoid flicker — the book's rule is simply the sign of the cross. The “since” date approximates by comparing history to TODAY'S policy rate.",
        read: "RECEIVE = the book's core easing-cycle trade: receive rates around the last hike and stay until the last cut is close. A small gap that just flipped sign is the interesting moment; a deep long-standing gap is late-cycle.",
        why: "The digest records easing-cycle receivers as its most reliable rates P&L (“strongly positive; carries well as the curve normalizes”); payers into hikes are recorded as less profitable. Case study: Brazil 2011 — 1Y crossed below policy on the day of the last hike, 12+ months of positive-carry receiving followed.",
        ref: "Digest section “Tradeable Frameworks — EM Rates”. Search: EM rate cycle receiver last hike · 1y swap vs policy rate turn signal" },
      { name: "R2 PEAK (chip: PEAKED / rising / flat)",
        what: "An inflation-cycle flag: PEAKED when CPI y/y sits at least 0.15pp below its trailing ~6-month maximum and is not rising; RISING when it's at/near the max and above the prior print; FLAT otherwise (steady-state — no cycle signal either way). A single sub-max month can flip it — it is a sensitive detector, not a confirmed-turn test.",
        read: "PEAKED + a hiking central bank = the hiking cycle is likely over. The book's finding: EM central banks stop hiking in the SAME MONTH inflation peaks (median), and at the first cut inflation is typically still ~130bp above the target band — direction matters more than level.",
        why: "This is the timing link between the inflation column and R1: you don't wait for inflation to be back at target to receive.",
        ref: "Digest “Critical Empirical Finding” under the rate-cycle rules. Search: EM central bank last hike inflation peak" },
      { name: "REAL and vs TGT · RK (with #rank chip)",
        what: "Two real-rate measures: policy − CPI y/y (REAL), and the book's preferred valuation metric policy − inflation-target midpoint (vs TGT), ranked across the universe. Green chip = top-3 (long candidates), red = bottom-3 (short candidates).",
        read: "R3 is a RELATIVE-value rule: long the top-3 real yields, short the bottom-3. The level matters less than the rank. A negative REAL with a high rank still qualifies as a long in a low-real-rate world.",
        why: "Real-rate ranking is the book's core cross-country rates valuation. It says the target-midpoint deflator beats realized CPI as the denominator.",
        ref: "Digest “Real Rate Valuation”. No Sharpe recorded in the digest for this rule. Search: EM real rates cross-country ranking · inflation target midpoint deflator" },
      { name: "R4 TP·z (term premium + its z-score)",
        what: "The term premium proxied as 5Y swap − policy rate, and its z-score over a rolling 3 months. Highlighted green when z > 1. (Fine print: the code subtracts the CURRENT policy rate as a constant from the 5Y history, so the z is exactly the z-score of the 5Y swap level over 63 days — the level column is the true premium; the z is the timing trigger.)",
        read: "z > 1 = the 5Y is unusually elevated versus policy → the book's signal to RECEIVE 5Y. This is a mean-reversion trade on the premium, not a duration view.",
        why: "The one rules-timing overlay with a recorded number: adding this filter improved the strategy Sharpe from 0.88 (buy-and-hold receiver) to 1.18 in the book's backtest.",
        ref: "Digest “Term Premium”. Search: EM term premium receive 5y · term premium z-score strategy" },
      { name: "R5 CURVE (pair, slope bp, 3m change)",
        what: "The curve slope in bp with its 3-month change in parentheses. The pair label is data-driven: 2s10s whenever the country's 2Y swap prices in the snapshot (all the profiled majors normally do), 1s10s otherwise (mostly frontier/GCC names).",
        read: "Read it against R1's phase: the book says 2s10s STEEPENERS start working months BEFORE the first cut (“receivers for chickens” — steepeners with less carry drag), and flatteners work into the first hike but less reliably.",
        why: "Curve trades let you express the cycle view with less outright-duration risk than R1.",
        ref: "Digest curve-cycle rules; the digest's only numbered book section, 6.21 “sliding down the slope”, is a RELATED but different cross-country slope-valuation strategy. Search: 2s10s steepener before first cut EM" },
      { name: "CARRY",
        what: "1M forward-implied yield minus SOFR — read LIVE from the Carry Basket service (the same number as that tab's yield rank). Not computed here.",
        read: "This is R7. Two conventions to know: it IS forward-points-based (the book's requirement — carry from forward points, not interest-rate differentials, which the book calls the most dangerous EM mistake a G10 trader can make), but it is USD-funded — and the book's headline evidence (IR 1.16 for the vol-adjusted basket) is JPY-FUNDED; it records USD-funded simple carry as money-losing since 2011.",
        why: "Carry is the book's anchor EMFX factor, but funding currency decides whether it has worked.",
        ref: "Digest carry sections. Search: vol-adjusted carry basket JPY funded · forward points vs rate differential carry" },
      { name: "R8 MOM (1M % + up-days/21)",
        what: "The currency's 1-month spot appreciation vs USD, plus breadth: how many of the last 21 trading days were up-days.",
        read: "Momentum confirms, it doesn't lead: green momentum + high breadth (say 14/21) = a trend you can join; breadth near 10/21 = chop, no signal.",
        why: "Digest records 1M vol-adjusted momentum at IR 0.86 (“degraded vs pre-2008 but still tradable”) and breadth at IR ~1.0 as a confirmation overlay.",
        ref: "Digest EMFX factor hierarchy. Search: EMFX one month momentum factor · market breadth up days currency" },
      { name: "R11 σ (stress count chip)",
        what: "How many of the trailing 100 trading days moved more than 1 daily standard deviation. Red chip when > 30 = statistically stressed.",
        read: "This is a PRECONDITION gauge, not a trade signal: the book's emergency-hike playbook says a defensive hike only rescues a currency that is already stressed (>30 σ-moves in 100d) AND cheap on REER. Only the σ-count half is computed here — the REER-cheapness half is not yet built, so check REER yourself before applying the playbook. The recorded failure pattern is on that missing half: a currency still EXPENSIVE on REER that hikes defensively tends to keep selling off.",
        why: "Digest records 12 of 20 emergency hikes “working” when preconditions were met — a small sample, flagged as such.",
        ref: "Digest “Event Trading Playbooks”. Search: emergency rate hike currency defense REER" },
      { name: "CDS",
        what: "5Y USD sovereign CDS spread (bp) — the market price of sovereign credit risk.",
        read: "Context column: a rules-attractive country with blowing-out CDS is telling you WHY the real rate is high. Compare within region, and watch the direction more than the level.",
        why: "Separates “cheap because unloved” from “cheap because insolvent”." },
      { name: "SCORE (final column)",
        what: "A HOUSE composite — explicitly NOT from the book: a vote across the rates rules. R1 RECEIVE +2 / PAY −2 · R2 peaked +1 / rising −1 / flat 0 (steady-state inflation is deliberately no signal — the book's R2 is a cycle-turn timer, so pegs and long-since-disinflated countries don't collect a standing PAY vote) · R3 rank top-3 +1 / bottom-3 −1 · R4 z>1 +1 · R11 stressed −1. Range roughly −5…+5; ≥+2 chips green “REC”, ≤−2 red “PAY”.",
        read: "Hover the cell to see which rules voted (an explicit 0 means computed-and-neutral; absent means not computable). A country with no computable rules shows “—”, never a defaulted zero — and compare scores only between countries with similar coverage; a frontier name scoring +1 on two rules is weaker evidence than a major scoring +1 on five. One vote to discount: R11's −1 comes from a PRECONDITION gauge running on half its conditions (the REER leg is unbuilt).",
        why: "It compresses the row into a single receive-vs-pay lean for triage — but the weights (2/1/1/1/1) are a judgment call, not backtested. Use it to decide which rows to read, not which trades to do." },
      { name: "R6 · RISK OVERLAY (global card, top-left)",
        what: "The book's rule: when the max 2-year z-score across five IMPLIED-vol surfaces (EMFX IV, G10 FX IV, US rates IV, S&P IV, oil IV) exceeds 2, cut EMFX carry exposure entirely; re-enter below 2. What this card actually computes: the max z across THREE realized-vol stand-ins — cross-sectional EM FX spot vol, US 10Y change vol, and Brent vol (VIX is shown live for context but is NOT in the max-z).",
        read: "⚠ KNOWN DEVIATION, flagged deliberately: our Workspace has no history entitlement for the implied-vol surfaces, so this card uses REALIZED-vol z-scores over a shorter window — and two of the book's five dimensions (equity vol, G10 FX vol) currently have NO stand-in at all, so a pure equity-vol shock would not trip it unless EMFX/rates/oil vols move too. The one place this dashboard knowingly deviates from source methodology; treat as indicative. The honest alternatives: leave the card blank until IV history is entitled, or keep it clearly labelled realized-vol (current choice).",
        why: "The overlay is what made the book's carry basket survivable — it is the risk-off circuit-breaker for everything else on this screen.",
        ref: "Digest risk-overlay section. Search: cross-asset vol z-score overlay carry" },
      { name: "R9 · UST 10Y Δ3M (global card)",
        what: "The 3-month (63 trading day) change in the US 10Y yield.",
        read: "Above +100bp the book records EMFX as “reliably negative” — a global headwind that overrides country-level signals. Case study: 2013 taper tantrum (Mexico's 10Y moved with beta ~1.4 to USTs).",
        ref: "Digest “Quantitative Thresholds”. Search: UST sell-off 100bp EMFX" },
      { name: "R10 · CNH 12M FWD (global card)",
        what: "The 12-month CNH forward's depreciation vs spot, in %.",
        read: "More than +5% priced depreciation = short-CNH positioning is extended — an inflection/squeeze signal for the whole EM complex, since China leads EM.",
        ref: "Digest “China as Leading Indicator”. Search: CNH 12 month forward positioning signal" },
    ],
    overlaps: [
      "CARRY here and the Carry Basket tab's yield rank are the SAME live number from the same service (/api/carry/rank) — deliberately, so a carry figure never disagrees between tabs. The Carry Basket tab is where you act on it (build and size the basket); this tab is where it sits alongside the other rules.",
      "Policy rates and CPI here are country-level snapshots; the SG Fundamentals tab is the deep, model-grade version of the same question for one country. The intent is one deep-dive per country over time, with this screener as the cross-country index.",
    ],
    integrity: [
      { cls: "live", item: "Swaps, OIS, bonds, CDS, spot, polls", note: "All rule inputs are fetched from LSEG at build time (verified RIC map in SG_FUNDAMENTALS_PLAN.md §3.1). Cached 12h; the build stamp top-right (under REBUILD) shows when." },
      { cls: "official", item: "Inflation-target midpoints (R3 vs TGT)", note: "Per-country hardcoded table of official central-bank target midpoints — transcriptions of published targets, not market data. If a target regime changes, this table must be updated by hand." },
      { cls: "model", item: "R6 risk overlay", note: "Realized-vol stand-in for the book's implied-vol surfaces (no IV history entitlement) — now labelled “realized-vol proxy” on the card itself. The single knowing methodology deviation on this tab — see the R6 entry above." },
      { cls: "model", item: "Rule trigger calibrations", note: "R1's −0.10/+0.25 bands, R2's peak-detection buffer (0.15pp below the ~6m max, not rising), and the neutral zones are house heuristics that operationalise the book's qualitative rules on live data." },
      { cls: "model", item: "SCORE column", note: "House composite (unweighted votes R1 ±2 · R2 ±1 · R3 ±1 · R4 +1 · R11 −1) — our aggregation for triage, not the book's, and not backtested. “—” when no rule computed." },
      { cls: "gap", item: "Core CPI for IN / CO / KR / MY", note: "No verified core-CPI RIC — column is blank, not proxied." },
      { cls: "gap", item: "R11's REER leg · R12 event playbooks / R13 breakevens", note: "Not built yet — absent from the screen rather than approximated. The global cards now show “no data” (amber) rather than a benign default when an input is missing." },
      { cls: "gap", item: "Build-failure behaviour", note: "⚠ If the LSEG pull fails wholesale (rate-limit day), the build caches a near-empty matrix for up to 12h with a healthy-looking build stamp — a page full of dashes with a fresh timestamp means outage, not calm; hit REBUILD." },
    ],
    refs: [
      { label: "Willer, Chandran & Lam — Trading Fixed Income and FX in Emerging Markets: A Practitioner's Guide (Wiley 2020, ISBN 978-1-119-59905-0)",
        note: "the source for every rule. The digest in the em-macro-trader skill records section names and only one chapter number (6.21) — so citations above point at digest sections; check the physical book to pin pages.",
        search: ["Willer Chandran Lam emerging markets book", "Citi EM strategy trading rules"] },
      { label: "Evidence caveats",
        note: "digest backtests end ~2018 (in-sample since); IRs are pre-funding-cost; tail rules (R11) rest on ~20 events. The book's foundational framing: ~65% of EMFX returns are global-factor-driven, ~36% for local rates — country selection is the minority of the P&L.",
        search: ["EM returns global factor share", "carry factor decay post 2011"] },
    ],
  },

  // ═══════════════════════ SG FUNDAMENTALS · MONITOR ═══════════════════════
  "fund.monitor": {
    title: "SG FUNDAMENTALS — MONITOR",
    tagline: "The official statistics MAS itself watches into each policy decision. Monthly/quarterly data, refreshed 6-hourly, never polled.",
    why: [
      "Singapore runs monetary policy through the exchange rate: MAS steers the S$NEER inside a band whose slope/width/centre it re-sets at each quarterly Monetary Policy Statement. The inputs to that decision are, per MAS's own published framework, core inflation versus its ~2% medium-term norm and the output gap. This tab replicates the indicator set MAS's Economic Policy Group charts in the Macroeconomic Review, so you can read the economy the way the policymaker does before the market does.",
      "Everything here is official statistics — LSEG economic-indicator series (aSG…), SingStat Table Builder, data.gov.sg — plus a small set of transcribed official facts (forecast ranges, MPS decisions, survey medians) that carry their vintage labels. One build every 6 hours; REFRESH forces it.",
    ],
    how: [
      { name: "Header stats (CPI · CORE · NEXT PRINT · MAS RANGE · OUTPUT GAP · MTI GDP)",
        what: "The current state of the two numbers policy reacts to (headline and MAS-core inflation), the next CPI release with the live Reuters-poll consensus, and the official goalposts: MAS's 2026 forecast range, the EPG output-gap estimate (+0.7%, MR Jul-26) and MTI's GDP range.",
        read: "MAS Core = headline CPI excluding accommodation and private road transport (together 35.6% of the basket) — the target variable. The header is the one-glance answer to \"where is inflation vs where MAS said it would be\".",
        why: "Core above the top of the MAS range with a positive output gap is the classic tightening configuration; the POLICY sub-tab turns this into an explicit reaction prior." },
      { name: "INFLATION (chart)",
        what: "Headline and MAS-core y/y, with the MAS 2026 forecast range shaded across calendar 2026.",
        read: "Watch where the lines sit inside the shaded band and their direction into the next MPS. The band is an annual AVERAGE forecast, so a month printing above it is not automatically a breach.",
        why: "This chart is the single most important input to the S$NEER slope decision." },
      { name: "CONTRIBUTIONS TO HEADLINE Y/Y (bars)",
        what: "A Laspeyres decomposition: each CPI component's weight × its index change ÷ last year's all-items index = its percentage-point contribution to headline y/y. Cyan bars are inside MAS core; amber bars (accommodation, private transport) are excluded.",
        read: "The question this answers: is inflation coming from things MAS reacts to (cyan) or things it looks through (amber)? A headline scare driven by amber bars (COE premiums, rents) gets a different policy response than the same number driven by services.",
        why: "Uses the official DOS 2024 weights (they sum to exactly 10,000); the same decomposition MAS publishes.",
        ref: "DOS 2024 CPI rebasing paper. Search: Singapore CPI 2024 rebasing weights · MAS core inflation definition" },
      { name: "CORE GROUPS (chart)",
        what: "The official MAS groupings inside core — Services, Retail & other goods, Electricity & gas — plus the official core series itself.",
        read: "Services is the persistent, wage-driven part (watch it for trend); electricity & gas is the administered, tariff-driven part (steps, not trends); retail goods is the imported part (NEER-sensitive, moves ~2 months before services per MR Oct-24 Box B)." },
      { name: "IMPORTED COSTS & S$NEER Y/Y (two charts)",
        what: "Import/export price indices y/y, and the official S$NEER's y/y appreciation.",
        read: "These are the imported-inflation channel. NEER appreciation dampens imported inflation: MAS's published pass-through estimate (MR Oct-24 Box B) is ~−2pp headline / −1pp core per +1pp NEER over 12 months (upper bound), goods before services.",
        why: "This is WHY the NEER slope is the policy instrument — it works through exactly these series.",
        ref: "MAS MR Oct-2024 Box B. Search: exchange rate pass-through Singapore NEER" },
      { name: "COE PREMIUMS (chart)",
        what: "COE = Certificate of Entitlement — the 10-year right to register a vehicle, auctioned by LTA in twice-monthly bidding exercises. Cat A = smaller/mass-market cars (≤1600cc & ≤130bhp, incl. mainstream EVs), Cat B = larger/luxury cars, Cat E = the open category usable for any vehicle (trades like B). The chart shows the auction clearing premium per exercise, same-day from data.gov.sg.",
        read: "Car prices in Singapore embed the COE premium, so premiums feed the private-road-transport CPI component (9.1% of the basket, EXCLUDED from core) with a 0–2 month lag. Rising premiums lift headline, not core.",
        why: "One of the few same-day observables for next month's CPI — which is why it appears again on the NOWCAST sub-tab. If data.gov.sg is unreachable (corporate firewall), the panel falls back to the LSEG-carried official PQP (Prevailing Quota Premium) — clearly relabelled, because PQP is a smoothed monthly average, not per-exercise premiums.",
        ref: "Search: COE bidding results LTA · certificate of entitlement CPI private transport" },
      { name: "RENTS & TARIFF",
        what: "URA private residential rental index y/y, plus the current SP Group electricity/gas tariff note.",
        read: "Accommodation CPI (26.6% of basket, excluded from core) is imputed from the STOCK of leases, so new-lease rents lead it by roughly 4–8 quarters — today's rent index tells you about accommodation CPI next year. The electricity tariff resets quarterly and steps utilities CPI deterministically.",
        why: "Both are excluded from core but a third of headline — the main reason headline and core diverge." },
      { name: "GDP & PMI · TRADE & PRODUCTION · DOMESTIC DEMAND & LABOUR",
        what: "The activity block: real GDP y/y (bars) with SIPMM PMI (50 = expansion/contraction line), NODX and industrial production y/y, retail volumes, unemployment and unit labour cost y/y.",
        read: "This is the output-gap side of the reaction function. ULC (unit labour cost) is MAS's central domestic-cost variable — services inflation follows it. Note the footer: resident wage series is a known gap (LSEG's is stale), disclosed rather than proxied." },
      { name: "MONEY & CREDIT",
        what: "M2 and bank lending y/y by segment.",
        read: "Context, not signal — Singapore does not target monetary aggregates; credit growth colours the financial-conditions picture." },
      { name: "MPS DECISIONS & RELEASE CALENDAR",
        what: "Every MPS outcome since 2016 in slope/width/centre shorthand (hand-transcribed from MAS statements, verified 2026-08-23), the SPF survey medians, and a ~6-month release calendar built from three layers: vendor-confirmed dates from the live Reuters polls, the hand-verified one-offs (MPS/MR, SPF, FX-intervention print), and “~”-prefixed recurrence ESTIMATES projected from each release's habitual day-of-month.",
        read: "The decision history is how you learn the reaction function empirically — match each ↑/↓/hold against where core and the output gap stood (POLICY sub-tab does this for you). In the calendar: amber = imminent, normal = confirmed date, dim with “~” = estimated timing (habitual day, NOT an announced date — a confirmed date replaces it as soon as the vendor carries one).",
        why: "⚠ maintenance note: the MPS decisions, SPF and forecast vintages remain manual transcriptions needing an update after the Oct-2026 MPS. The calendar extends itself for the recurring monthly/quarterly releases (MPS estimates use per-quarter habitual days: late-Jan/mid-Apr/late-Jul/mid-Oct); semi-annual one-offs like the FX-intervention print stay hand-maintained." },
    ],
    overlaps: [
      "COE premiums, rents and the tariff appear BOTH here and on NOWCAST — deliberately, at different frequencies for different jobs: here they are monthly/quarterly context for what already printed; on NOWCAST they are the same-day/weekly leads for the NEXT print. Same sources, same numbers where they overlap.",
      "S$NEER y/y here is the slow official series; the SGD NEER top-tab is the live intraday replica of the same index.",
      "The consensus row and next-print stats here feed the MODEL sub-tab, where the M1 nowcast is compared against exactly this consensus.",
    ],
    integrity: [
      { cls: "live", item: "All charts", note: "LSEG econ-indicator RICs (aSGCPI, aSGCPICOR, aSGIMPP/EXPP, aSGDEOP, aSGIP/C, aSGEXPDNO, aSGRSLSM/CA, aSGPMIRA, labour & money RICs), SingStat tables M213751/M213891/M015631/M212311, data.gov.sg COE. y/y lines are computed from official index levels." },
      { cls: "live", item: "Consensus (Reuters polls)", note: "Live snapshot of SG…=ECI poll RICs; each pre-release mean is also frozen to disk the moment it is seen, because LSEG stores no poll history — that vintage discipline is what makes the MODEL tab's surprise scorecard honest." },
      { cls: "official", item: "MAS range · output gap · MTI range · MPS decisions · SPF medians · tariff note · calendar", note: "Hand-transcribed published facts, each labelled with its vintage (MPS 27-Jul-26, MR Jul-26, MTI 11-Aug-26, SPF Jun-26, SP Group Q3-26). Verified against sources on 2026-08-23; they do NOT update themselves." },
      { cls: "gap", item: "Resident wage growth", note: "LSEG's wage series is stale (2024-Q3); pending a MOM source it is left out — noted in the footer, not proxied." },
      { cls: "gap", item: "LSEG outage behaviour", note: "A failed LSEG pull renders an empty chart / \"—\" (fail-empty, never fail-proxy), but the stale-source badge in the header only covers the SingStat and data.gov.sg feeds (FAO is flagged on the NOWCAST tab), not LSEG itself — an empty chart could be an outage or missing data." },
      { cls: "gap", item: "Corporate-firewall networks", note: "Networks that block SingStat/data.gov.sg for Python (while the browser gets through via a PAC proxy) blank the affected panels — each now says so explicitly instead of rendering empty. Fix: set EXT_DATA_PROXY (e.g. http://proxy.corp:8080) before starting the backend; LSEG-fed panels are unaffected, and the COE panel falls back to the labelled LSEG PQP series." },
    ],
    refs: [
      { label: "MAS Macroeconomic Review (quarterly, same day as each MPS)", note: "the source of truth this tab replicates; the statistical appendix has every series.", search: ["MAS macroeconomic review", "MAS monetary policy statement S$NEER"] },
      { label: "BIS Papers 142 — “Recent inflation dynamics in Singapore” (MAS EPG)", note: "MAS's published inflation model — the MODEL sub-tab implements a monthly version.", search: ["BIS papers 142 Singapore inflation"] },
      { label: "MAS Staff Paper 2025/1 (trimmed-mean core measures)", note: "why MAS now also charts the 25% trimmed mean.", search: ["MAS staff paper trimmed mean core inflation"] },
    ],
  },

  // ═══════════════════════ SG FUNDAMENTALS · MODEL ═══════════════════════
  "fund.model": {
    title: "SG FUNDAMENTALS — MODEL",
    tagline: "Our own inflation models: M1 answers “what will the next CPI print be?”; M2 explains why and projects six months out.",
    why: [
      "This tab holds the two models WE built and own. Pedigree, stated honestly: M2 (the Phillips curve) is a monthly adaptation of the reduced-form core-inflation equation MAS itself published in BIS Papers 142 — with one known simplification: the paper's wage term is not implemented (NEER and GST terms are added instead). M1 (the bottom-up component nowcast) is NOT a MAS product: it is the standard practitioner technique (forecast each CPI component, aggregate with official weights) that sell-side economics teams use, built here from scratch with the lag structures MAS documents in its Review boxes (tariff mechanics, rent lags; food currently runs on seasonals, not a pass-through driver). Neither model is endorsed by MAS; both are validated the only honest way — by backtest against what actually printed.",
      "What is being nowcast, precisely: the next UNPUBLISHED month of Singapore CPI (the target month is shown in the header, e.g. “M1 NOWCAST · Jul-26”), as headline y/y and MAS-core y/y. The NOWCAST sub-tab shows this model's high-frequency INPUTS; this tab shows the OUTPUT.",
    ],
    how: [
      { name: "Header: M1 NOWCAST vs CONSENSUS vs NAIVE",
        what: "The model's call for the next print (headline and core), the Reuters-poll consensus for the same print, and the naive benchmark (last month's y/y carried forward).",
        read: "The nowcast only earns attention if it beats naive in the backtest (the RMSE stats at right, green when it does). SURPRISE CALL is the disciplined way to use it: the model-minus-consensus edge only counts as a call when it exceeds half the backtest RMSE — inside that band it is noise and the header says so.",
        why: "CPI surprises move SGD rates and the NEER expectation — a validated directional call before the print is the whole point of the tab." },
      { name: "COMPONENT NOWCAST (table)",
        what: "All 14 CPI components: official weight, the model's m/m forecast, implied y/y, contribution to headline (pp), and the METHOD column saying exactly how each was forecast. ✕ marks components excluded from MAS core.",
        read: "Three components get real driver models — utilities (the announced SP tariff step × an estimated pass-through), private transport (OLS on COE bidding premiums, lags 0–1), accommodation (URA rents at 3–6 quarter lags, converted to a monthly crawl). Everything else uses that calendar month's median m/m over 6 years (ex-2020). The METHOD column is the honesty column: “seasonal” means no driver, and “(0 events)” after the tariff pass-through means the 0.8 pass-through is an assumption, not an estimate.",
        why: "Reading WHICH component drives the call tells you whether to trust it — a call driven by a known tariff step is near-deterministic; one driven by a seasonal median is soft." },
      { name: "BACKTEST — HEADLINE Y/Y (chart)",
        what: "Expanding-window, one-step-ahead re-forecast of the last 36 prints: for each month, every seasonal median and driver regression was refit using ONLY data available before that print (no lookahead), then compared to the actual and to naive.",
        read: "Look for the amber line (M1) hugging the cyan (actual) tighter than the dotted grey (naive), especially at turning points — that is where a nowcast pays. The RMSEs in the header summarise it.",
        why: "One caveat, disclosed: the backtest runs on today's data vintages, not point-in-time snapshots — acceptable for SG CPI (rarely revised) and COE/tariff (never revised)." },
      { name: "M2 — CORE PHILLIPS CURVE (chart)",
        what: "OLS: core y/y on its own lag, an output-gap proxy (HP-filtered industrial production), import-price y/y (lag 3), NEER y/y (lag 6, dampening), and GST step dummies (Jan-23, Jan-24). Fit from 2012; r² and n shown in the panel title.",
        read: "The fitted line is IN-SAMPLE (and the HP filter is two-sided, which flatters it) — judge M2 by whether its story is coherent, not by the fit. Only M1 is backtested out-of-sample.",
        why: "M2 is the explainer: it decomposes core into momentum (own lag), demand (IP gap), imported-cost and exchange-rate terms — in the spirit of the BIS-142 graph, minus the paper's wage term (not implemented here, so no wage bar will ever appear).",
        ref: "BIS Papers 142 (MAS EPG). Search: BIS 142 Singapore Phillips curve core inflation" },
      { name: "DECOMPOSITION & PROJECTION",
        what: "The latest month's core y/y split into coefficient × value contributions (pp) per term, and a 6-month projection.",
        read: "The decomposition answers “what has been driving core” — historically for Singapore the imported terms dominate (BIS-142's own finding for 2022; the paper also found wage pass-through “relatively small”, part of why the wage term was dropped from this monthly version). The projection is assumption-driven and says so: import prices and NEER held at last observation, IP gap decaying 0.9/month, GST dummies on the calendar. It is a conditional path, not a forecast with a confidence band." },
      { name: "SURPRISE SCORECARD",
        what: "One row per scored print: the consensus frozen before release, the model's frozen call, the actual, the surprise, and whether the model called the surprise's direction.",
        read: "This is the model's live track record, recorded FORWARD from 24 Aug 2026 (the vendor stores no consensus history, so no backfilled rows are possible — an honest empty table beats a fabricated history). Judge the model on hit rate once n is meaningful (~12+ rows).",
        why: "Forces vintage discipline: neither the consensus nor the model call can be retro-fitted after the print." },
    ],
    overlaps: [
      "The header's “M1 NOWCAST” is the OUTPUT; the NOWCAST sub-tab is the INPUT dashboard (tariff windows, COE, FAO, rents, Brent) for exactly this number — the naming is admittedly close; remember: MODEL = the answer, NOWCAST = the leading indicators.",
      "CONSENSUS here is the same live Reuters poll shown on MONITOR. The reaction-prior stat on POLICY consumes this tab's core nowcast.",
    ],
    integrity: [
      { cls: "live", item: "All model inputs", note: "SingStat CPI components (M213751/M213891), SingStat tariff series, URA rents, data.gov.sg COE bidding results, LSEG aSG series for M2. Nothing synthetic enters the models." },
      { cls: "official", item: "Weights · GST dates · tariff steps", note: "DOS 2024 weights (sum to exactly 10,000; a reconstruction check re-aggregates the latest published month and shows the % gap vs the official index — displayed in the header). Announced SP tariff steps are hand-maintained: ⚠ the Q4-26 step (announced ~end-Sep) must be added by hand or the Oct utilities forecast silently degrades to seasonal." },
      { cls: "model", item: "Every forecast number", note: "M1/M2 outputs are model estimates, labelled as such (“bottom-up”, “fitted”, “projection”). The tariff pass-through defaults to an assumed 0.8 when no historical step exists (“(0 events)” in the METHOD column). If the COE feed fails, the transport model can refit on LSEG's smoothed PQP series — a poorer driver; the r² gate usually rejects it back to labelled seasonal." },
      { cls: "gap", item: "Consensus history", note: "LSEG stores none (error 96104) — hence the forward-recorded scorecard instead of a backfilled comparison." },
      { cls: "gap", item: "Corporate-firewall networks", note: "M1 cannot run without the SingStat CPI component tables — on a network that blocks them the tab shows an explicit “unavailable” banner (only the LSEG-fed consensus survives), never a degraded model. Fix: EXT_DATA_PROXY to the corporate proxy before starting the backend." },
    ],
    refs: [
      { label: "BIS Papers 142 — the published MAS core equation", note: "M2's specification source; read it to see what the terms mean economically.", search: ["BIS papers 142 MAS EPG inflation"] },
      { label: "Bottom-up CPI nowcasting (practitioner technique)", note: "M1's approach — component forecasts × official weights; standard on sell-side econ desks, not a MAS methodology.", search: ["bottom-up CPI nowcast components", "inflation nowcasting methods central banks"] },
      { label: "MAS MR boxes used for lag structure", note: "MR Apr-17 Box B (food pass-through), MR Oct-24 Box B (NEER pass-through), DOS rebasing paper (weights, rental equivalence).", search: ["MAS macroeconomic review box exchange rate pass-through"] },
    ],
  },

  // ═══════════════════════ SG FUNDAMENTALS · NOWCAST ═══════════════════════
  "fund.nowcast": {
    title: "SG FUNDAMENTALS — NOWCAST",
    tagline: "The daily/weekly observables that LEAD the monthly CPI print. Inputs, not outputs — the output number lives on MODEL.",
    why: [
      "Singapore CPI prints on the ~23rd of each month. This tab exists to see that print FORMING beforehand, from prices that update daily or weekly: Brent inside the tariff-setting windows, COE auction results, the FAO food index, HDB rents, jet fuel. Nothing on this page is itself a CPI forecast — each panel is a leading indicator with a documented transmission channel and lag into a specific CPI component. The single output number these feed is the M1 nowcast on the MODEL sub-tab.",
      "Whose method is this? The tariff-window mechanics follow SP Group's own published reset methodology; the food-price pass-through and the rent→accommodation lead (4–8 quarters) come from MAS's published Review boxes; assembling them into a high-frequency watch-list is standard practitioner nowcasting (the style of PriceStats / sell-side trackers), built in-house. It is not a MAS product.",
    ],
    how: [
      { name: "TARIFF NOW · NEXT-Q TARIFF EST (stats) + BRENT & THE TARIFF-SETTING WINDOWS (chart)",
        what: "SP Group resets the regulated electricity tariff every quarter, mechanically, from the average oil-indexed gas price over the FIRST 2.5 MONTHS OF THE PRIOR QUARTER. The chart shades that window twice: grey = the window that set the current tariff, cyan = the still-forming window that will set the next one. The EST stat compares Brent's average in the two windows, scaled by the energy component's ~80% share of the bill.",
        read: "Because the window is mechanical and known in advance, this is the closest thing to a deterministic CPI input: by mid-quarter you largely know next quarter's utilities step before SP announces it (~2 weeks before quarter-start). “Window Xd in” warns you when the forming window is still thin. Two stated assumptions: Brent stands in for the oil-indexed gas price (labelled PROXY in the note — the one knowing input-proxy on this tab), and the partial window predicts the full one.",
        why: "Utilities steps are inside MAS core (electricity & gas) — unlike COE and rents, this one moves the number MAS reacts to.",
        ref: "SP Group quarterly tariff methodology + historical tariff xlsx. Search: SP Group electricity tariff methodology Singapore" },
      { name: "COE PREMIUMS (chart)",
        what: "COE = Certificate of Entitlement, the auctioned 10-year right to register a vehicle (twice-monthly LTA bidding exercises). Cat A = smaller/mass-market cars (≤1600cc & ≤130bhp, incl. mainstream EVs) · Cat B = larger/luxury cars · Cat E = open category, valid for any vehicle, in practice trades like B. Same-day results from data.gov.sg.",
        read: "Premiums flow into the private-road-transport CPI component (9.1% of basket, EXCLUDED from core) with a 0–2 month lag — the MODEL tab's transport component regresses directly on these. A 10k jump in Cat A/B is worth watching for the next two headline prints; core is untouched.",
        why: "This is the same series as MONITOR's COE panel — repeated here because between CPI prints it is one of the only same-day inflation observables." },
      { name: "FAO FOOD PRICE INDEX (chart)",
        what: "The FAO global food price index, y/y — a free monthly series from fao.org.",
        read: "MAS's own analysis (MR Apr-2017 Box B, per the verified research record) finds a 0.63 long-run pass-through from global food prices into Singapore's food import price index, with roughly half of the IPI→CPI pass-through arriving within 4 quarters. Rising FAO y/y today = food CPI pressure over the coming quarters.",
        ref: "MAS MR Apr-2017 Box B. Search: FAO food price index · food price pass-through Singapore CPI" },
      { name: "HDB RENTS (chart)",
        what: "The average of town-level MEDIAN 4-room HDB rents, from the data.gov.sg median-rent-by-town dataset (quarterly).",
        read: "Accommodation CPI (26.6% of basket, excluded from core) is imputed from the stock of existing leases, so NEW-lease rents lead it by ~4–8 quarters. This series is a leading indicator, never accommodation CPI itself. Construction caveats, stated: unweighted mean across towns (mix shifts can move it without rents moving), 4-room only.",
        why: "Rents are the slowest-burning but largest excluded component — today's rent trend is next year's headline/core wedge." },
      { name: "JET FUEL (SGP FOB SWAP)",
        what: "Singapore jet-kerosene swap (M1) — the cost input to airfares/travel services CPI.",
        read: "When the RIC is not entitled on this Workspace the panel deliberately shows NOTHING with a note saying so — that is the house no-proxy rule in action, and the pattern every other panel follows on failure.",
        why: "Airfares sit inside core services; jet fuel leads them." },
      { name: "Footer: KNOWN GAPS",
        what: "The explicit list of feeds we do NOT have (e.g. weekly pump prices — no verified source yet; the experimental scraped supermarket basket was deliberately deferred).",
        read: "If a feed is not on this page, it is in this list — absence is declared, never papered over." },
    ],
    overlaps: [
      "COE, rents and the tariff also appear on MONITOR — same sources, different job: MONITOR gives the official monthly/quarterly context; this tab gives the higher-frequency lead on the next print.",
      "Everything here is an input to the M1 nowcast on MODEL — that tab's COMPONENT NOWCAST table shows exactly how each of these series enters (and its METHOD column tells you when one didn't).",
    ],
    integrity: [
      { cls: "live", item: "Brent · COE · FAO · HDB rents · jet fuel", note: "LSEG LCOc1 / JETSGSWMc1, data.gov.sg (COE same-day, HDB median rents quarterly), fao.org CSV. FAO/HDB/COE carry stale flags from the fetch layer — now surfaced as an amber “stale:” note next to the build stamp." },
      { cls: "official", item: "Current tariff (31.91¢, energy 25.50¢, Q3-26)", note: "Hand-transcribed from SP Group's announcement. ⚠ The window arithmetic rolls forward automatically each quarter but these constants do NOT — from ~end-Sep 2026 (Q4 announcement) they must be hand-updated or TARIFF NOW and the EST's base go stale; the as-of chip shows the vintage so you can catch it." },
      { cls: "model", item: "NEXT-Q TARIFF EST", note: "A labelled estimate: window Brent ratio × ~80% energy share, with Brent as a stated proxy for the oil-indexed gas price. Early in a quarter it rests on few prints — check “window Xd in”." },
      { cls: "gap", item: "Pump prices · scraped price basket · jet fuel (if unentitled)", note: "Declared gaps — shown as nothing plus a note, per the house rule." },
      { cls: "gap", item: "Corporate-firewall networks", note: "COE/FAO/HDB panels flag themselves “unavailable” when this network blocks data.gov.sg/fao.org for Python (Brent and the tariff windows are LSEG/hardcoded and survive). Fix: set EXT_DATA_PROXY to the corporate proxy before starting the backend." },
    ],
    refs: [
      { label: "Nowcasting as practitioners do it", note: "high-frequency indicator baskets mapped to CPI components — the PriceStats/“billion prices” lineage.", search: ["billion prices project PriceStats", "high frequency inflation nowcasting indicators"] },
      { label: "MAS MR Apr-2017 Box B (food) · DOS rental-equivalence method (rents)", note: "the published transmission channels this tab's lags come from.", search: ["MAS food price pass-through box", "rental equivalence accommodation CPI Singapore"] },
    ],
  },

  // ═══════════════════════ SG FUNDAMENTALS · POLICY ═══════════════════════
  "fund.policy": {
    title: "SG FUNDAMENTALS — POLICY",
    tagline: "What the published MAS reaction function implies for the next MPS, against the full decision history.",
    why: [
      "MAS is unusually legible: it has PUBLISHED an estimate of its own reaction function. MR Oct-2018 Box A shows the band slope responding to the core-inflation gap (vs a ~2% medium-term norm) and the output gap; MR Oct-2021 Special Feature A quantifies it: +1pp of expected inflation ≈ +1.7% NEER appreciation, +1pp of output gap ≈ +0.9%. This tab feeds our model's core nowcast and MAS's own output-gap estimate into that published rule to produce a REACTION PRIOR for the next meeting, and lines it up against what forecasters expect (SPF) and what MAS has actually done since 2016.",
    ],
    how: [
      { name: "Header stats (NEXT MPS · REACTION PRIOR · SPF OCT SLOPE · M2 CORE @ MPS)",
        what: "The next meeting date (no later than 14 Oct 2026), the rule-implied stance from the model tab's core nowcast + the +0.7% output gap, the share of SPF respondents expecting an October slope-up (30%, Jun-26 survey), and where the M2 Phillips projection puts core at the meeting.",
        read: "The stance labels (TIGHTENING BIAS / NEUTRAL-TO-TIGHTENING / NEUTRAL) are OUR thresholds on the core nowcast (>2.0 / >1.5), not MAS language — the published part is the sensitivities, the read is house judgment. When the model hasn't built, this shows “—” rather than a default.",
        why: "The trade around an MPS is rich when the rule, the survey and the market disagree — this row shows all three." },
      { name: "POLICY REACTION FRAMEWORK (panel)",
        what: "The rule in words, with the current inputs filled in live: core nowcast, its gap to ~2%, the MR Jul-26 output gap, and the Phillips projection's direction (computed from the live projection, not hardcoded).",
        read: "Mind the anchor: the ~2% core norm is MAS's oft-repeated “just under 2%” language, paraphrased — MAS has no announced numerical inflation target. Treat the whole panel as a disciplined prior, not a prediction: MAS also weighs financial-stability and external considerations the rule omits.",
        ref: "MR Oct-2018 Box A · MR Oct-2021 SF A. Search: MAS monetary policy reaction function · MAS NEER slope core inflation output gap" },
      { name: "2026 FORECAST VINTAGES (table)",
        what: "MAS's 2026 core/headline forecast range, statement by statement (Oct-25 baseline → raised Jan-26 → raised Apr-26 on the energy shock → held Jul-26).",
        read: "Vintage revisions ARE the policy signal: a central bank raising its own forecast path is telling you which way the risk to the slope points. SPF medians sitting in the upper half of the MAS range corroborates." },
      { name: "MPS DECISION HISTORY (table)",
        what: "Every decision since 2016 in slope/width/centre shorthand: ↑/↓ slope = faster/slower appreciation (the workhorse move), widen band = volatility regime (Oct-2010 style), re-centre = a step change in the level (the crisis/inflection tool), slope→0% = neutral (COVID).",
        read: "Read it against the inflation chart on MONITOR: the 2022 sequence (two off-cycle tightenings) is the reaction function under stress; the 2025 easings are it working in reverse. This is the training set for your intuition on what October looks like.",
        why: "Hand-transcribed from MAS statements and verified 2026-08-23 — a maintenance point, not a data feed." },
    ],
    overlaps: [
      "REACTION PRIOR and M2 CORE come from the MODEL tab's payload; the decision history and vintages also appear condensed on MONITOR. The SGD NEER top-tab is where a slope change would actually print — via the band estimates there.",
    ],
    integrity: [
      { cls: "official", item: "Sensitivities (+1.7% / +0.9%) · decisions · vintages · SPF · next-meeting date", note: "Transcriptions of published MAS material (MR boxes, MPS statements, SPF Jun-26 Table 4), vintage-labelled. ⚠ All hand-maintained: after the Oct-2026 MPS the decisions table, vintages, SPF and both next-meeting literals need manual updates. One SPF detail (70% “hold”) is inferred as the remainder of the 30% slope-up figure rather than read from the table — it is not displayed anywhere." },
      { cls: "model", item: "REACTION PRIOR read · core gap · Phillips path direction", note: "Model-derived (labelled “from model”) plus house thresholds. The ~2% anchor is a paraphrase of MAS language, not an announced target. Fails to “—” when the model is unavailable — never defaults." },
    ],
    refs: [
      { label: "MAS MR Oct-2018 Box A (the estimated rule) · MR Oct-2021 SF A (the sensitivities)", note: "read these two boxes and this tab explains itself.", search: ["MAS reaction function box Oct 2018", "MAS NEER policy rule estimate"] },
      { label: "MAS Survey of Professional Forecasters", note: "quarterly; Table 4 has respondents' expected band moves at coming meetings.", search: ["MAS survey professional forecasters table"] },
    ],
  },

  // ═══════════════════════ SGD NEER · MONITOR ═══════════════════════
  "neer.monitor": {
    title: "SGD NEER — MONITOR",
    tagline: "A live replica of MAS's policy instrument: where the S$NEER sits inside an ESTIMATED policy band, tick by tick.",
    why: [
      "MAS's policy instrument is not an interest rate — it is the trade-weighted S$NEER, steered inside a band (a midpoint crawling upward at an appreciation “slope”, ± a width). MAS publishes the NEER's weekly-average LEVEL with a lag, but discloses neither the basket weights nor any band parameter. So a live monitor must reconstruct all of it — and this one is explicit about which parts are reconstruction.",
      "Three estimated layers, stated up front: (1) the basket WEIGHTS are street estimates attributed to Barclays (USD ~20%, EUR ~15%, CNY-via-CNH ~15%, …13 currencies); (2) the live INDEX is our geometric replica from 13 live spots, re-scaled to match the latest official weekly print; (3) the BAND (±2% width, the slope schedule, the +166bp-above-mid anchor at the Jul-26 MPS) is street consensus. The Calibration panel exists to keep layer (1)–(2) honest against the official series; layer (3) cannot be validated — MAS never confirms it.",
    ],
    how: [
      { name: "Big readout + S$NEER Live Index",
        what: "The replica index (scaled to the official ~141 level), with the latest OFFICIAL weekly aSGDEOP value and its date printed directly beneath — so you always see the real anchor next to the live estimate.",
        read: "If the official line shows “—”, the re-scale has no anchor and the level reverts to an internal base — treat the level as unscaled until it returns." },
      { name: "BAND POSITION (gauge)",
        what: "Where the live replica sits between the estimated floor and ceiling, in bp from the midpoint, with RICH/CHEAP/NEUTRAL zones.",
        read: "Position is the trading state: the gauge labels RICH from +50bp (a quarter of the half-width; the marker turns red from ~+130bp), and the last stretch before the ceiling is where the cap really binds — MAS limits further appreciation, so risk/reward favours fading SGD strength; near the floor the reverse, with the added kicker that MAS defends the floor. The gauge inherits the anchor estimate's error 1:1 — a ±20bp anchor error shifts every reading ±20bp, which is why the zones matter more than the digits.",
        why: "Band position is the single number this whole tab exists to produce." },
      { name: "LIVE INTRADAY (chart)",
        what: "The replica at minute/hourly bars (1D–20D windows), y-axis fitted to the tick range, band lines drawn only if they fall inside it. Polls 60s, visible tab only.",
        read: "Off-hours the Asian legs don't tick and are held flat, so quiet stretches understate movement; bars implying a >0.6% index jump are dropped as bad data." },
      { name: "BAND HISTORY (chart)",
        what: "About two years of daily replica (the history fetch is capped at 760 days) vs the estimated band, with MPS actions from Jan-2025 onward marked (green ease · red tighten · blue re-centre · grey hold).",
        read: "Two things to learn from it: how the NEER travels the band between meetings (it spends most time in the upper half in tightening regimes), and what each action did to the crawl. ⚠ The band is drawn BACKWARD from the Jul-26 anchor using today's estimated slope schedule — historical band positions are an ex-post reconstruction, good for intuition, not for backtesting (see the ANALYSIS tab's caveat)." },
      { name: "BASKET COMPOSITION (table)",
        what: "The 13 legs: estimated weight, live RIC quote, the bilateral SGD rate, and each leg's bp contribution to today's NEER move. CNH stands in for CNY (the tradable proxy — disclosed); ⁻¹ marks quotes inverted into the basket.",
        read: "The CONTRIB column decomposes today's NEER move: SGD strong because USD is weak everywhere (broad amber legs) is very different from SGD strong on its own (one-sided). Weights are Barclays estimates — the Calibration panel refits them against the official series to show they're close." },
      { name: "SORA / OIS (panel)",
        what: "The overnight SORA fixing (MAS-published) vs the O/N OIS swap, and the full SORA OIS curve to 30Y — all live.",
        read: "The domestic rates leg of the SGD story: because MAS fixes the FX path, SGD rates float as the residual — SORA OIS reprices when band expectations change. A sudden OIS drop with a stable NEER usually means appreciation expectations rose." },
      { name: "CARRY (panel)",
        what: "Forward-NEER minus spot-NEER per tenor (the same basket built from each leg's forward outright), annualised, and NET carry = the estimated policy slope minus that forward-priced appreciation.",
        read: "If forwards price MORE appreciation than the slope delivers, being long SGD costs carry (negative NET) — you are paying for appreciation that policy may not deliver. NET carry embeds the ESTIMATED slope, so read its sign with the slope uncertainty in mind.",
        why: "This is the cost side of every band trade: fading the ceiling earns the position AND the carry when NET is positive." },
      { name: "CALIBRATION (panel)",
        what: "Replica vs official, month-average frequency: tracking error (bp), correlation, R², and a constrained re-fit of the 13 weights against the official series (BARCLAYS% vs FITTED% vs Δ).",
        read: "This is the honesty panel. TE in the low-teens bp with r² ≥0.95 means the weight estimates are good enough to trade band position; a deteriorating fit means MAS re-weighted (it re-bases periodically) and the weights need refreshing.",
        why: "Without this panel the whole tab would be an unvalidated model — with it, two of the three estimated layers are continuously checked." },
      { name: "TRADING METRICS (grid)",
        what: "Statistics of the band-position series: z-score and percentile vs its own history, bp distances to ceiling and floor (plus a σ-distance for the ceiling only), realized vol, 20/50-day MA deviations, carry-to-vol.",
        read: "Mind the unit on “Ceiling dist σ”: it is measured in ANNUALIZED-vol sigmas — 1σ ≈ a typical YEAR's move, so divide by √52 (≈7) to think in weeks. The MA-deviation z-scores are the ANALYSIS tab's signal in miniature." },
    ],
    overlaps: [
      "MONITOR's S$NEER y/y chart on SG Fundamentals is the official series this replica is scaled and validated against. The POLICY sub-tab (SG Fundamentals) explains WHY the slope moves; this tab shows the slope's effect live. Net carry here and the Carry Basket tab measure different things: this is SGD-basket carry vs the policy slope; that is USD-funded cross-sectional carry.",
    ],
    integrity: [
      { cls: "live", item: "13 spot legs · SORA fixing & OIS curve · forwards/NDF outrights · official weekly NEER", note: "All LSEG, RICs shown in the tables. Official series: aSGDEOP weekly (falls back to the monthly official series if unavailable — both official, the source string discloses which)." },
      { cls: "model", item: "Basket weights · band width ±2% · slope schedule · +166bp anchor", note: "Street estimates (Barclays-attributed weights; “consensus” width; per-MPS slope estimates). MAS discloses none of them. Labelled on the tab since this manual shipped; the Calibration panel validates the weights, nothing can validate the band. A ±20bp anchor error shifts every band-position reading equally." },
      { cls: "model", item: "NET carry", note: "Market forwards (live) minus the ESTIMATED slope — the market half is hard, the slope half is street judgment." },
      { cls: "gap", item: "Official fetch failure", note: "If the official series can't be fetched the replica displays unscaled (base-100) rather than inventing a level — visible because the official line under the big number goes blank." },
    ],
    refs: [
      { label: "MAS on the exchange-rate-centred framework", note: "the official description of band/slope/width policy.", search: ["MAS exchange rate centred monetary policy explained", "S$NEER policy band slope width"] },
      { label: "Street NEER models", note: "every house maintains one (Barclays', whose weights these are, is the reference here); comparing replicas is a cottage industry.", search: ["SGD NEER model basket weights estimate", "Barclays SGD NEER"] },
    ],
  },

  // ═══════════════════════ SGD NEER · ANALYSIS ═══════════════════════
  "neer.analysis": {
    title: "SGD NEER — ANALYSIS",
    tagline: "Is band position mean-reverting, and is the reversion tradable? A signal scan with two honestly-separated backtests.",
    why: [
      "The economic logic: inside a credible band, position mean-reverts — the closer the NEER drifts to the ceiling, the more MAS leans against it (and the market knows it), so extremes tend to fade back toward the crawl. This tab quantifies that: it detrends band position, fades 2σ extremes, and asks two DIFFERENT questions — does the signal predict the index (signal quality), and could you have monetised it trading USD/SGD (tradability). Conflating those two is the classic NEER-strategy mistake; the tab keeps them as separate backtests.",
    ],
    how: [
      { name: "BAND POSITION — MEAN REVERSION (signal chart)",
        what: "Band position % (replica vs crawling midpoint) with Bollinger bands (20-day, ±2σ) and the fade signals: BUY triangles when position breaks 2σ cheap, SELL when 2σ rich. Signals beyond ±1.4% band position — i.e. within ~60bp of the ±2% wall — render dimmed (“fighting-cap” conviction).",
        read: "The high-conviction setup is a 2σ extreme NEAR a band edge in the fade direction — statistics and the policy cap agree. A dimmed signal means the z-score wants to fade but you'd be short gamma against MAS." },
      { name: "TREND (SMA20 vs SMA50)",
        what: "The same band-position series with its 20- and 50-day moving averages.",
        read: "Regime filter: when SMA20 is decisively above SMA50 the NEER is trending up the band and fades against it underperform — take only the with-trend side, or stand aside." },
      { name: "BACKTEST ① — signal on the index (gross)",
        what: "The fade strategy applied to the S$NEER index itself, gross of everything, position taken from yesterday's signal (no same-day execution).",
        read: "This measures ONLY whether the signal predicts the index — the S$NEER is not a tradable instrument, so this equity curve is a diagnostic, never a P&L. That caption is on the chart for a reason." },
      { name: "BACKTEST ② — traded via USD/SGD (net)",
        what: "The same signal executed in USD/SGD, net of an assumed 0.4bp/side spread and 3%/yr carry drag (both stated on the panel).",
        read: "This is the realizable version, with two drags: transaction costs, and basket tracking error — USD is only ~20% of the NEER basket, so USD/SGD tracks the signal imperfectly. Expect ② well below ①; the gap is the cost of the NEER not being tradable.",
        why: "Sharpe here, not in ①, is the number that decides whether this is a strategy or a curiosity." },
      { name: "Stats per block (Total/Ann return · Sharpe · MaxDD · Hit rate · Trades/yr)",
        read: "Trades/yr matters most for believing the rest: a handful of trades per year means wide confidence bands on everything else. Rolling Sharpe shows regime dependence — mean reversion pays in stable-band regimes and bleeds around re-centrings." },
    ],
    overlaps: [
      "The signal is a formalisation of the MA-deviation z-scores on the MONITOR's Trading Metrics grid. MPS meeting dates (the regime breaks in this data) are on the MONITOR's band history and SG Fundamentals POLICY tab.",
    ],
    integrity: [
      { cls: "model", item: "The whole tab", note: "Everything is conditioned on the ESTIMATED band (width/slope/anchor — see the MONITOR manual). The tab's own footer says it plainly: band parameters are reverse-engineered; signals are illustrative." },
      { cls: "model", item: "Backtest lookahead — the honest caveat", note: "The historical band is drawn BACKWARD from the Jul-2026 anchor using today's slope schedule, so historical band positions embed information unavailable at the time. Partially mitigated because the signal fades a 20-day rolling mean (the level largely cancels), but the “fighting-cap” conviction tags depend on the ex-post band. Treat results as an upper bound on the edge." },
      { cls: "model", item: "Cost & carry assumptions", note: "0.4bp/side and 3%/yr are stated constants, not measured from your fills; the true carry drag varies with the forward curve (the MONITOR's carry panel shows the live version)." },
      { cls: "live", item: "Underlying series", note: "Replica NEER from live LSEG spots and USD/SGD daily history — the raw data is real throughout; it is the band overlay that is estimated." },
    ],
    refs: [
      { label: "Bollinger bands / z-score mean reversion", note: "the signal is textbook; the edge, if any, comes from the band cap, not the statistics.", search: ["bollinger band mean reversion strategy", "z-score fade strategy FX"] },
      { label: "Trading the SGD band", note: "the practitioner literature on NEER-band strategies (fade-the-edges, re-centring event trades).", search: ["trading SGD NEER band strategy", "MAS re-centring trade"] },
    ],
  },

  // ═══════════════════════ CARRY BASKET ═══════════════════════
  carry: {
    title: "CARRY BASKET",
    tagline: "Rank every traded currency by 1M forward-implied yield, then build a vol-balanced long/short carry book from live pricing.",
    why: [
      "Carry — earning the yield differential while spot stands still — is the anchor EM FX factor. This tool does it the way the Willer/Chandran/Lam book insists it must be done: carry is computed from FORWARD POINTS (covered interest parity), never from interest-rate differentials — the book calls rate-differential carry “the single most dangerous mistake G10 traders make in EM”, because cross-currency basis makes the two diverge and only the forward is what you actually trade.",
      "Mechanics: for each of 33 EM + 9 G10 currencies, take live spot and the live 1M forward (NDF for restricted names), back out the yield the forward implicitly pays via CIP (Act/360, holiday-adjusted day counts, proper USD discount curve from live 1M SOFR OIS). Carry = that implied yield − 1M SOFR: what you earn over USD funding if spot doesn't move. One convention caveat the book makes essential: this rank is USD-FUNDED — the book's best evidence (IR 1.16 for the vol-adjusted basket) is JPY-funded, and it records USD-funded simple carry as money-losing since 2011. Use the rank as relative value, not as proof the strategy prints.",
    ],
    how: [
      { name: "YIELD RANK (table, right)",
        what: "All currencies sorted by 1M forward-implied yield vs USD. Columns: rank, pair, group (EM/G10), implied yield %, carry % (yield − SOFR), d = the actual day count to the 1M value date (holiday-adjusted, matches the pricer), and L/S toggles.",
        read: "NDF tags mark offshore-implied yields (the tradable number for restricted currencies — it embeds onshore/offshore basis, deliberately). A “—” means the forward is genuinely unpriced right now: the tool refuses to fake a yield from spot alone. The top of the rank is usually high-nominal-yield EM (TRY, EGP, NGN...) — exactly the names where the crash caveat below matters most." },
      { name: "BASKET CONSTRUCTION (controls, left)",
        what: "Pick longs (top-N fill or per-name) with USD notionals; pick shorts; choose short sizing (vol-neutral vs $-neutral), within-leg weighting (inverse-vol vs equal-notional), and the vol lookback window.",
        read: "Vol-neutral (default) sizes the short leg so its daily $-vol equals the long leg's — a $10mm long in a 0.3%/day currency is $30k/day of risk, so a 0.6%/day short only needs $5mm. Inverse-vol within a leg equalises risk per name (the book's construction — it improves IR 30–50% across strategies — though the book uses prior-year realized vol while this tool's windows top out at 90d). $-neutral / equal-notional are the index conventions, there for comparison.",
        why: "Sizing is where carry baskets are won or lost — unsized, the highest-yielders (which are also the most crash-prone) dominate the risk." },
      { name: "SIZED BOOK (panel)",
        what: "The computed book: leg notionals, per-name and book daily $-vol, diversification benefit, net carry $/yr, carry-to-vol, parametric VaR95/99.",
        read: "Book vol comes from the FULL covariance of the basket's daily returns with signed exposures — not the sum of leg vols — so the diversification % tells you how much the long/short structure nets out. Carry-to-vol is an ex-ante Sharpe proxy: the amber box explains why not to trust it alone (carry is structurally short-vol and negatively skewed; realized vol UNDERPRICES tail risk, especially for managed/pegged names). Read it with the per-leg Down95/Down99 columns — those are the actual worst historical daily moves applied to your size.",
        why: "The book's risk overlay (R6 on EM Rules) exists precisely because this number looks best right before it's worst." },
      { name: "β EM (rank column)",
        what: "Rolling beta of the currency's daily appreciation returns against an equal-weight EM FX basket, over the selected vol-lookback window.",
        read: "β≈1 = the currency IS the EM complex; β≈0 = it dances to its own tune (or is pegged — pegs also damp the basket itself); β<0 = safe-haven (JPY/CHF-style) — shorting THOSE concentrates risk-off pain, the classic JPY-funded-carry profile, not neutral funding. Funder selection use: shorting a HIGH-β name makes the basket partly an EM risk-off hedge; shorting a low-POSITIVE-β name is the purer funding trade. Statistical health warning: β over 10/20 days is noise (sampling error ±0.3–0.5) — use the 60/90d windows for selection; short-window β is for watching regime shifts, not ranking funders.",
        why: "Carry books die in risk-off; knowing each leg's β to the complex is how you shape what the basket does on the bad day. (First load after opening the tab pulls the full universe's histories — expect the column to fill after several seconds; cached ~2h.)",
        ref: "Search: currency beta to EM FX index · funding currency selection carry trade" },
      { name: "BASKET HISTORY — 20y cumulative P&L (button: LOAD 20Y)",
        what: "Replays TODAY'S sized book through ~20 years of monthly carry-trade excess returns: per leg r = F(1M,t)/S(t+1M) − 1 — the textbook definition, in which the USD funding leg cancels, so no historical USD rate is assumed (nothing proxied). Signed current notionals held constant → the chart is additive cumulative P&L in USD, not a compounded NAV.",
        read: "What to look for: the long grind up (carry accrues) punctuated by cliffs (2008, 2013 taper, 2015 CNY, 2020, 2022) — the shape IS the short-vol, negatively-skewed profile the crash caveat warns about. Check the coverage line: a leg enters only when its composite 1M points history begins (broker-only names like EGP/NGN mostly won't appear), early years may hold fewer legs than today's book, and “gap-mo” counts a leg's INTERIOR data gaps — which cluster in exactly the crisis months (sanctions, NDF seizure), so the cliffs can be UNDERSTATED. Also mid-to-mid: no transaction costs are charged, and ~12 rolls/yr flatters wide-spread NDF legs. Worst-month stat is your one-month tail on this exact book.",
        why: "The rank shows what carry PAYS; this shows what holding it COSTS in the bad months — both halves of the trade.",
        ref: "Search: carry trade excess return forward discount · currency carry crash 2008" },
      { name: "Per-leg table columns (Carry% · Vol%/d · $vol/d · Down95/99%)",
        read: "Down95/Down99 are empirical percentiles of the actual return window, not normal-distribution numbers — when they're much fatter than 1.65×/2.33× the daily vol, the tail is telling you the vol number is a lie for that name.",
        why: "A currency with 8% carry and a −4% Down99 is a different trade from one with 5% carry and −1.2%." },
    ],
    overlaps: [
      "The CARRY column on EM Rules is read live from THIS service — same number, one source of truth. The vol/window machinery matches Risk Units; the day-count engine matches the pricer (verified to <1bp on 40/42 names at last check).",
      "SGD's NET carry on the NEER tab is a different concept: basket-forward vs policy slope, not USD-funded implied yield.",
    ],
    integrity: [
      { cls: "live", item: "Spots · forward points/outrights · SOFR OIS", note: "Single batched LSEG snapshot ~90s (frontend polls 120s, visible tab only). Missing forwards yield “—”, never a fake number. If the live 1M SOFR quote is unavailable the entire rank now FAILS VISIBLY (amber banner) instead of silently substituting an assumed rate — that silent 4.3% fallback existed and was removed on 2026-08-24 under the no-proxy rule." },
      { cls: "live", item: "EGP / NGN yields", note: "Broker-sourced by instruction: EGP = average of two live broker quotes that genuinely disagree (GMGM points vs FMD outright, ~2pp apart); NGN = single broker outright. Live but thin — treat those two yields as indicative." },
      { cls: "model", item: "Vols & VaR & β", note: "Realized daily log-return vol of SPOT (swap-point vol ignored — immaterial at 1M for most names, less so for EGP/NGN/TRY); parametric VaR assumes normal; “Down99” on a 20d window is literally the worst single day; β is vs an equal-weight EM basket that includes pegged names (damping it) and each name's own ~1/n self-weight." },
      { cls: "model", item: "20y basket history", note: "Real prices throughout (daily spot + composite 1M points, month-end sampled — per-leg month-ends can differ by a few days), but five stated approximations: calendar-month hold for the exact 1M roll; today's notionals constant across 20 years; legs absent before their history starts AND during interior data gaps (crisis-clustered — cliffs understated; gap months disclosed per leg); mid-to-mid with NO transaction costs (~12 rolls/yr flatters wide NDF spreads); multi-month gaps are skipped, never bridged. Illustrative of the profile, not an executable track record." },
      { cls: "gap", item: "Vol history failures", note: "A failed history fetch excludes that name from sizing (amber “no vol history” note) for up to 2h rather than proxying — the remaining shorts absorb the risk target, so re-check sizing when the note shows." },
      { cls: "gap", item: "Quote timestamps", note: "The as-of stamp is the build date; thin broker NDF quotes can be older than it. A timestamp field per quote is a known gap." },
    ],
    refs: [
      { label: "Willer/Chandran/Lam — carry chapters", note: "forward-points carry, inverse-vol sizing, JPY-vs-USD funding evidence (IR 1.16 JPY-funded; USD-funded broken since 2011), and the vol overlay that makes it survivable.", search: ["vol-adjusted carry basket EM FX", "JPY funded carry trade emerging markets", "cross currency basis carry forward points"] },
      { label: "Carry crash literature", note: "why carry-to-vol flatters: peso problem, crash risk, short-vol structure.", search: ["carry trade crash risk skewness", "peso problem currency carry"] },
    ],
  },

  // ═══════════════════════ RISK UNITS ═══════════════════════
  risk: {
    title: "RISK UNITS",
    tagline: "State a USD risk budget — get the position size. The sizing question asked in the right direction.",
    why: [
      "Most tools answer “how much risk does $X mm have?”. A trader sizing a trade needs the inverse: “I'm willing to lose $100k/day of vol (or $Y of VaR95) — how big can the position be?”. This tool does that for any currency and product the pricer knows: state the budget, it returns the notional (for spot/outrights) or the DV01 (for curve trades).",
      "The math is deliberately simple and visible: size = target daily $-vol ÷ the product's measured daily vol. VaR95/99 are just 1.645×/2.326× daily vol under a normal assumption — and the tool shows the HISTORICAL version next to the parametric one so you can see when the real tail is fatter than the normal one.",
    ],
    how: [
      { name: "Inputs (left)",
        what: "Currency → product (Spot, SP×1M…12M outrights, or fwd-fwd curve trades like 3M×6M) → vol lookback window (10/20/60/90d) → the risk target: a USD amount interpreted as Daily Vol, VaR95 or VaR99.",
        read: "Products carry their unit: NOTIONAL products size in USD mm; DV01 products (fwd-fwds — lending/borrowing the currency between two forward dates) size in USD per basis point. 20d window = responsive to the current regime; 60/90d = stable through it. Only changing ccy/product/window refetches data — typing amounts recomputes locally.",
        why: "VaR95 input ÷ 1.645 = the same daily-vol budget; the three metrics are one number in three units — pick the one your limits are written in." },
      { name: "SIZE TO PUT ON (headline)",
        what: "The computed position: USD mm notional, or USD/bp DV01, with the underlying level and measured vol beneath (window and observation count shown).",
        read: "Sanity-check the vol line before trusting the size: a 10d window after a quiet week will hand you a dangerously large position — that is the tool obeying you, not advising you." },
      { name: "Risk profile table (Parametric $ vs Historical $)",
        what: "Daily vol, VaR95, VaR99 in dollars — parametric (z × σ) beside historical (the actual worst 5%/1% days of the window applied to the computed size).",
        read: "Historical ≫ parametric = fat tails in this window; trust the historical. Caveat at short windows: “historical VaR99” on 20 observations is literally the single worst day — a min, not a percentile.",
        why: "The parametric/historical gap is the cheapest fat-tail detector you'll ever get." },
      { name: "Fwd-fwd products — how their vol is built",
        what: "For curve trades the tool rebuilds the fwd-fwd implied yield's daily history from spot + near/far forward points via the discount-factor engine, then measures the stdev of its daily CHANGES in bp.",
        read: "One modelling shortcut, disclosed: the USD (SOFR) leg is FROZEN at today's level across the whole 400-day history — EM swap-point moves dwarf daily SOFR moves, but it means USD-rate-driven vol is invisible here. Day counts in this engine also use a 30.44-day month approximation (not the holiday calendar the carry tab uses) — a few bp on levels, immaterial to vol.",
        why: "DV01 sizing on curve trades is what makes fwd-fwd positions comparable to outrights in one risk budget." },
    ],
    overlaps: [
      "Same LSEG price histories and window conventions as the Carry Basket's vol engine; same z-constants. Carry sizes a BOOK to balance legs; this sizes ONE product to a budget — use this for the entry ticket, that for the portfolio.",
    ],
    integrity: [
      { cls: "live", item: "Price histories & levels", note: "LSEG daily BID/ASK history (400d) per spot/points RIC; on-demand per (ccy, product, window), cached 15min. Missing history errors honestly (amber note) — e.g. 12×18 fwd-fwds for NDF names always error because the composite 18M RIC doesn't exist." },
      { cls: "live", item: "SOFR leg", note: "Live SOFR OIS snapshot. If unavailable, the fwd-fwd calc now FAILS VISIBLY instead of silently assuming a rate — that hardcoded 4.3% fallback was removed 2026-08-24 under the no-proxy rule." },
      { cls: "model", item: "Parametric VaR · frozen-SOFR fwd-fwd history · 30.44-day counts", note: "Stated assumptions (normal tails; USD leg frozen across history; average-month day counts in the fwd-fwd engine only). The historical column exists precisely to check the first one." },
      { cls: "gap", item: "BWP curve products", note: "⚠ Known defect, flagged rather than hidden: BWP's inverted quote convention is not handled by this tab's fwd-fwd engine, so BWP DV01 products compute with the ratio upside-down (spot vol/notional sizing is unaffected). Don't use BWP fwd-fwd numbers until fixed." },
    ],
    refs: [
      { label: "Vol targeting / risk-unit sizing", note: "the practitioner standard this implements (Carver's “risk units”, bank vol-targeting frameworks).", search: ["volatility targeting position sizing", "value at risk parametric vs historical"] },
      { label: "FX forward-forward trades", note: "what a 3M×6M actually is and why its risk is a DV01.", search: ["FX forward forward swap points curve trade", "NDF curve trade DV01"] },
    ],
  },
};
